export const defaultHostility = [
  {
    AlwaysEnemies: [
      "assault",
      "marksman",
      "pmcUSEC",
      "pmcBEAR",
      "pmcBot",
      "exUsec",
      "pmcBot",
      "bossBully",
      "bossBoar",
      "bossTagilla",
      "bossKilla",
      "bossKojaniy",
      "bossSanitar",
      "bossKolontay",
      "bossGluhar",
      "bossKnight",
      "sectantPriest",
      "sectantWarrior",
    ],
    AlwaysFriends: [
      "bossZryachiy",
      "followerZryachiy",
      "peacefullZryachiyEvent",
      "ravangeZryachiyEvent",
      "gifter",
    ],
    BearEnemyChance: 100,
    BearPlayerBehaviour: "AlwaysEnemies",
    BotRole: "pmcBEAR",
    ChancedEnemies: [],
    Neutral: [],
    SavagePlayerBehaviour: "AlwaysEnemies",
    UsecEnemyChance: 100,
    UsecPlayerBehaviour: "AlwaysEnemies",
    Warn: ["sectactPriestEvent"],
  },
  {
    AlwaysEnemies: [
      "assault",
      "marksman",
      "pmcUSEC",
      "pmcBEAR",
      "pmcBot",
      "exUsec",
      "pmcBot",
      "bossBully",
      "bossBoar",
      "bossTagilla",
      "bossKilla",
      "bossKojaniy",
      "bossSanitar",
      "bossKolontay",
      "bossGluhar",
      "bossKnight",
      "sectantPriest",
      "sectantWarrior",
    ],
    AlwaysFriends: [
      "bossZryachiy",
      "followerZryachiy",
      "peacefullZryachiyEvent",
      "ravangeZryachiyEvent",
      "gifter",
    ],
    BearEnemyChance: 100,
    BearPlayerBehaviour: "AlwaysEnemies",
    BotRole: "pmcUSEC",
    ChancedEnemies: [],
    Neutral: [],
    SavagePlayerBehaviour: "AlwaysEnemies",
    UsecEnemyChance: 100,
    UsecPlayerBehaviour: "AlwaysEnemies",
    Warn: ["sectactPriestEvent"],
  },
];

export const configLocations = [
  "customs",
  "factoryDay",
  "factoryNight",
  "interchange",
  "laboratory",
  "lighthouse",
  "rezervbase",
  "shoreline",
  "tarkovstreets",
  "woods",
  "gzLow",
  "gzHigh",
];

export const originalMapList = [
  "bigmap",
  "factory4_day",
  "factory4_night",
  "interchange",
  "laboratory",
  "lighthouse",
  "rezervbase",
  "shoreline",
  "tarkovstreets",
  "woods",
  "sandbox",
  "sandbox_high",
];
